#!/usr/bin/env bash

set -Eeo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")"
source "install-shared.bash"

subm_dir="rust-fil-sector-builder"

git submodule update --init --recursive $subm_dir

if download_release_tarball tarball_path "${subm_dir}"; then
    tmp_dir=$(mktemp -d)
    tar -C "$tmp_dir" -xzf "$tarball_path"

    mkdir -p ./bin

    cp "${tmp_dir}/bin/paramfetch" ./bin/
    cp "${tmp_dir}/include/sector_builder_ffi.h" .
    cp "${tmp_dir}/lib/libsector_builder_ffi.a" .
    cp "${tmp_dir}/lib/pkgconfig/sector_builder_ffi.pc" .
else
    echo "failed to find or obtain precompiled assets for ${subm_dir}, falling back to local build"
    build_from_source "${subm_dir}"

    mkdir -p include
    mkdir -p lib/pkgconfig

    find "${subm_dir}" -type f -name sector_builder_ffi.h -exec cp -- "{}" . \;
    find "${subm_dir}" -type f -name libsector_builder_ffi.a -exec cp -- "{}" . \;
    find "${subm_dir}" -type f -name sector_builder_ffi.pc -exec cp -- "{}" . \;

    # TODO https://github.com/filecoin-project/rust-fil-sector-builder/issues/39
    FP_VERSION=$(cat ${subm_dir}/Cargo.lock | grep 'name = "filecoin-proofs"' -A1 | tail -n1 | cut -d' ' -f3 | tr -d '"')

    pushd ${subm_dir}

    cargo install --version $FP_VERSION filecoin-proofs --force --root .. --bin paramfetch || true

    popd
fi
