// Code generated by "stringer -type=State"; DO NOT EDIT.

package sealing_state

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[Pending-1]
	_ = x[Failed-2]
	_ = x[Sealing-3]
	_ = x[Sealed-4]
	_ = x[Paused-5]
	_ = x[ReadyForSealing-6]
}

const _State_name = "UnknownPendingFailedSealingSealedPausedReadyForSealing"

var _State_index = [...]uint8{0, 7, 14, 20, 27, 33, 39, 54}

func (i State) String() string {
	if i < 0 || i >= State(len(_State_index)-1) {
		return "State(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _State_name[_State_index[i]:_State_index[i+1]]
}
