version: 2.1

jobs:
  build_and_test_linux:
    docker:
      - image: circleci/golang:1.12.1-stretch
    working_directory: /tmp/go/src/github.com/filecoin-project/go-sectorbuilder
    resource_class: xlarge
    steps:
      - configure_env
      - install_rust
      - install_go_linux
      - checkout
      - update_submodules
      - build_project_dependencies
      - lint_project
      - restore_parameter_cache
      - obtain_filecoin_parameters
      - save_parameter_cache
      - test_project
  build_and_test_darwin:
    macos:
      xcode: "10.0.0"
    working_directory: /tmp/go/src/github.com/filecoin-project/go-sectorbuilder
    resource_class: medium
    steps:
      - run:
          name: Install pkg-config
          command: HOMEBREW_NO_AUTO_UPDATE=1 brew install pkg-config
      - configure_env
      - install_rust
      - install_go_darwin
      - checkout
      - update_submodules
      - build_project_dependencies
      - lint_project
      - restore_parameter_cache
      - obtain_filecoin_parameters
      - save_parameter_cache
      - test_project

workflows:
  version: 2
  test_all:
    jobs:
      - build_and_test_linux
      - build_and_test_darwin

commands:
  install_go_darwin:
    steps:
      - run:
          name: Install go
          command: |
            curl https://dl.google.com/go/go1.12.1.darwin-amd64.pkg -o /tmp/go.pkg
            sudo installer -pkg /tmp/go.pkg -target /
            go version
  install_go_linux:
    steps:
      - run:
          name: Install go
          command: |
            curl https://dl.google.com/go/go1.12.linux-amd64.tar.gz -o /tmp/go.tar.gz
            tar -C /usr/local -xzf /tmp/go.tar.gz
            go version
  configure_env:
    steps:
      - run:
          name: Configure environment variables
          command: |
            echo 'export CARGO_HOME=/tmp/cargo' >> $BASH_ENV
            echo 'export FILECOIN_PARAMETER_CACHE="/tmp/filecoin-parameter-cache"' >> $BASH_ENV
            echo 'export GO111MODULE=on' >> $BASH_ENV
            echo 'export GOPATH="/tmp/go"' >> $BASH_ENV
            echo 'export PATH=${PATH}:/usr/local/go/bin:${CARGO_HOME}/bin' >> $BASH_ENV
            echo 'export RUST_BACKTRACE=1' >> $BASH_ENV
            echo 'export RUST_LOG=info' >> $BASH_ENV
            echo 'export RUSTUP_HOME=/tmp/rustup' >> $BASH_ENV
            source $BASH_ENV
  obtain_filecoin_parameters:
    steps:
      - run:
          name: Generate Groth parameters and verifying keys for 1KiB sectors
          command: |
            paramcache --test-only
  update_submodules:
    steps:
      - run:
          name: Update submodules
          command: git submodule update --init --recursive
  build_project_dependencies:
    steps:
      - run:
          name: Build project dependencies
          command: make
  lint_project:
    steps:
      - run:
          name: Lint project
          command: go run github.com/golangci/golangci-lint/cmd/golangci-lint run
  test_project:
    steps:
      - run:
          name: Test project
          command: RUST_LOG=info go test
  restore_parameter_cache:
    steps:
      - restore_cache:
          keys:
            - v1b-proof-params-{{ checksum "paramfetch" }}
  save_parameter_cache:
    steps:
      - save_cache:
          key: v1b-proof-params-{{ checksum "paramfetch" }}
          paths:
            - /tmp/filecoin-parameter-cache
  install_rust:
    steps:
      - run:
          name: Install Rust
          command: |
            curl https://sh.rustup.rs -sSf | sh -s -- -y